import { FormRules } from 'element-plus';

const requiredTextRule = { required: true, message: 'Поле должно быть заполнено', trigger: 'blur' };

export const rules: FormRules = {
  'primary.typePerc': [ requiredTextRule ],
  'primary.typeReq': [ requiredTextRule ],
  'percData.inn': [ requiredTextRule ],
  'percData.kpp': [ requiredTextRule ],
  'percData.egrip': [ requiredTextRule ],
  'percData.shortname': [ requiredTextRule ],
  'percData.fullname': [ requiredTextRule ],
  'percData.phone': [ requiredTextRule ],
  'percData.email': [
    requiredTextRule,
    { type: 'email', message: 'Введите корректный email', trigger: ['blur'], }
  ],
  'account.number': [ requiredTextRule ],
  'account.bik': [ requiredTextRule ],
  'account.korr': [ requiredTextRule ],
  'account.name': [ requiredTextRule ],
  'account.address': [ requiredTextRule ],
  'gazData.from': [ { type: 'date', required: true, message: 'Поле должно быть датой', trigger: 'change' } ],
  'gazData.yearCapacity': [ requiredTextRule ],
  'clientData.dir': [ requiredTextRule ],
  'clientData.pos': [ requiredTextRule ],
  'clientData.phone': [ requiredTextRule ],
  'clientData.gazHoz.name': [ requiredTextRule ],
  'clientData.gazHoz.pos': [ requiredTextRule ],
  'clientData.gazHoz.phone': [ requiredTextRule ],
  'clientData.curator': [ requiredTextRule ],
  'generalData.plan': [ requiredTextRule ],
  'generalData.currentYear': [ requiredTextRule ],
  'generalData.currentYearSuppose': [ requiredTextRule ],
  'generalData.factLastYear': [ requiredTextRule ],
  'generalData.factDeviation': [ requiredTextRule ],
  'generalData.periodLastYear': [ { required: true, type: 'array', message: 'Поле должно быть заполнено', trigger: 'blur' } ],
  'generalData.count': [ requiredTextRule ],
  'generalData.reason': [ { required: true, message: 'Поле должно быть заполнено', trigger: 'change' } ],
  'generalData.financeCurrentYear': [ requiredTextRule ],
  'generalData.costCurrentYear': [ requiredTextRule ],
  'energyNas.fuelReduce': [ requiredTextRule ],
  'energyNas.gasSrc': [ requiredTextRule ],
  'energyNas.total': [ requiredTextRule ],
  'energyNas.tcj': [ requiredTextRule ],
  'energyNas.budget': [ requiredTextRule ],
  'energyNas.otherProd': [ requiredTextRule ],
  'energyNas.energyPerc': [ requiredTextRule ],
  'energyNas.src': [ requiredTextRule ],
  'energyTco.totalItems': [ requiredTextRule ],
  'energyTco.srcDataSt9': [ requiredTextRule ],
  'energyTco.energyTotal': [ requiredTextRule ],
  'energyTco.srcDataSt11': [ requiredTextRule ],
  'energyTco.gasPercProd': [ requiredTextRule ],
  'energyTco.gasPercNas': [ requiredTextRule ],
  'energyTco.condition': [ requiredTextRule ],
};
